site_name: Cell Fate Explorer
repo_url: https://github.com/HuangDDU/CellFateExplorer
repo_name: HuangDDU/CellFateExplorer

nav:
  - Home: index.md
  - Tutorial:
      - Quick Start: tutorial/quickstart.ipynb
  - API:
      - API Summary: api.md
      - Data:
          - FateAnnData: api/data/fate_anndata.md
          - MilestoneWrapper: api/data/fate_milestone_wrapper.md
          - WaypointWrapper: api/data/fate_waypoint_wrapper.md

      - Method:
          - FateMethod: api/method/fate_method.md

      - Metric:
          - TopologyMetric: api/metric/topology_metric.md
          - ClusterMetric: api/metric/cluster_metric.md
          
      - Plot:
          - plot_trajectory: api/plot/plot_trajectory.md
  - Shedule: 
      - Shedule Summary: shedule.md
      - Data: shedule/data.md
      - Method: shedule/method.md
      - Plot: shedule/plot.md
      - Benchmark: shedule/benchmark.md
      - Downstream Analysis: shedule/downstream_analysis.md
      - Website: shedule/website.md

  - Change Log: change_log.md

theme:
  name: material
  language: en
  custom_dir: docs/overrides/
  features:
    # - navigation.expand
    - navigation.tracking
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
  icon:
    repo: fontawesome/brands/github

plugins:
  - search
  - tags
  - git-revision-date-localized:
      type: datetime
      locale: zh
  - git-committers:
      repository: https://github.com/HuangDDU/CellFateExplorer
      branch: dev
  - bibtex:
      bib_file: "docs/references.bib"
  - mkdocs-jupyter:
  - mkdocstrings:
      default_handler: python
      ignore:
        - '^{#refs}$'  # 忽略 {#refs}
      handlers:
        python:
          # import: cfe
          options:
            show_root_heading: true
            show_symbol_type_heading: true
            # show_source: false
          selection:
            docstring_style: google


markdown_extensions:
  - footnotes